# Site settings
title: CVEU Workshop
email: caba@adobe.com
url: https://example.github.io
description: "ICCV 2021 Workshop on AI for Creative Video Editing and Understanding."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  links: "#219ab3"

organizer:
  - name: Fabian Caba Heilbron
    affliation: Adobe Research
    avatar: https://fabiancaba.com/img/fabian.png
    website: "#!"
  - name: Yu Xiong
    affliation: The Chinese University of Hong Kong
    avatar: http://www.xiongyu.me/src/yu_sq.jpg
    website: http://xiongyu.me

# Footer settings
footer: AI for Creative Video Editing and Understanding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/FabianCabaH
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/CVEU

# Build settings
markdown: kramdown
permalink: pretty
