# Site settings
title: CVEU Workshop
email: caba@adobe.com
url: https://example.github.io
description: "ICCV 2021 Workshop on AI for Creative Video Editing and Understanding."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  links: "#219ab3"

organizer:
  - name: Fabian Caba Heilbron
    affliation: Adobe Research
    avatar: https://fabiancaba.com/img/fabian.png
    website: "#!"
  - name: Yu Xiong
    affliation: The Chinese University of Hong Kong
    avatar: /img/avatar/yu_xiong.jpg
    website: http://xiongyu.me
  - name: Alejandro Pardo
    affliation: KAUST
    avatar: https://avatars.githubusercontent.com/u/16939779?v=4
    website: https://github.com/PardoAlejo
  - name: Anyi Rao
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=8lKr7j4AAAAJ&citpid=3&authuser=1
    website: https://anyirao.com/
  - name: Qingqiu Huang
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=RIfPt_MAAAAJ&citpid=3
    website: http://qqhuang.cn/
  - name: Ali Thabet
    affliation: KAUST
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=7T0CPEkAAAAJ&citpid=5
    website: https://www.alithabet.com/
  - name: Victor Escorcia
    affliation: Samsung
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=VDrK6cYAAAAJ&citpid=2
    website: https://escorciav.github.io/
  - name: Dong Liu
    affliation: Netflix
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=NvU30c4AAAAJ&citpid=12
    website: https://scholar.google.com/citations?user=NvU30c4AAAAJ&hl=zh-CN
  - name: Dahua lin
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=GMzzRRUAAAAJ&citpid=3
    website: http://dahua.site/
  - name: Bernard Ghanem
    affliation: KAUST
    avatar: /img/avatar/bernard.jpg
    website: http://www.bernardghanem.com/

# Footer settings
footer: AI for Creative Video Editing and Understanding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cveu_workshop
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/CVEU

# Build settings
markdown: kramdown
permalink: pretty
