# Site settings
title: CVEU Workshop
# email: cveu.ai@gmail.com
email: cveu_organizers@googlegroups.com
url: https://cveu.github.io
description: "ICCV 2021 Workshop on AI for Creative Video Editing and Understanding."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: "#000000"
  links: "#219ab3"

organizer:
  - name: Fabian Caba Heilbron
    affliation: Adobe Research
    avatar: https://fabiancaba.com/img/fabian.png
    website: "#!"
  - name: Yu Xiong
    affliation: The Chinese University of Hong Kong
    avatar: /img/avatar/yu_xiong.jpg
    website: http://xiongyu.me
  - name: Alejandro Pardo
    affliation: KAUST
    avatar: https://avatars.githubusercontent.com/u/16939779?v=4
    website: https://github.com/PardoAlejo
  - name: Anyi Rao
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=8lKr7j4AAAAJ&citpid=3&authuser=1
    website: https://anyirao.com/
  - name: Qingqiu Huang
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=RIfPt_MAAAAJ&citpid=3
    website: http://qqhuang.cn/
  - name: Ali Thabet
    affliation: KAUST
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=7T0CPEkAAAAJ&citpid=5
    website: https://www.alithabet.com/
  - name: Victor Escorcia
    affliation: Samsung
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=VDrK6cYAAAAJ&citpid=2
    website: https://escorciav.github.io/
  - name: Dong Liu
    affliation: Netflix
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=NvU30c4AAAAJ&citpid=12
    website: https://scholar.google.com/citations?user=NvU30c4AAAAJ&hl=zh-CN
  - name: Dahua lin
    affliation: The Chinese University of Hong Kong
    avatar: https://scholar.googleusercontent.com/citations?view_op=medium_photo&user=GMzzRRUAAAAJ&citpid=3
    website: http://dahua.site/
  - name: Bernard Ghanem
    affliation: KAUST
    avatar: /img/avatar/bernard.jpg
    website: http://www.bernardghanem.com/

speaker:
  - name: James E. Cutting
    affliation: Cornell University
    avatar: /img/avatar/james-e-cutting.jpeg
    website: http://people.psych.cornell.edu/~jec7/index.htm
  - name: Irfan Essa
    affliation: Georgia Tech; Google
    avatar: /img/avatar/irfan-essa.jpeg
    website: http://www.irfanessa.gatech.edu/
  - name: Marc Christie
    affliation: University of Rennes 1; IRISA/INRIA
    avatar: /img/avatar/marc-christie.jpeg
    website: http://people.irisa.fr/Marc.Christie/
  - name: Maneesh Agrawala
    affliation: Stanford University
    avatar: http://graphics.stanford.edu/~maneesh/images/agrawala-macarthur3-head-square.jpg
    website: http://graphics.stanford.edu/~maneesh/
  - name: Angjoo Kanazawa
    affliation: UC Berkeley; Google
    avatar: /img/avatar/angjoo.jpeg
    website: http://people.eecs.berkeley.edu/~kanazawa/

industry:
  - name: Adobe
    logo: /img/avatar/adobe.png
  - name: Netflix
    logo: /img/avatar/netflix.png
  - name: Facebook
    logo: /img/avatar/facebook.png
  - name: Google
    logo: /img/avatar/google.png
  - name: Tencent
    logo: /img/avatar/tencent.png
  - name: TikTok (Bytedance)
    logo: /img/avatar/tiktok.png

# Footer settings
footer: AI for Creative Video Editing and Understanding

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/cveu_workshop
  - title: github
    url: https://github.com/CVEU
  - title: discord
    url: https://discord.gg/f3K5xGbX
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll

# Build settings
markdown: kramdown
permalink: pretty
